### PR TITLE
Removed List<T> class

### PR DESCRIPTION
**Pull request by marcusnaslund**
Merges `List<T>` and `ArrayList<T>` in preparation for adding our own `List` implementation in #1248

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Peer review @sebastianbaginski ?

**Comment by sebastianbaginski** [comment]
I guess most of the code is just moved. I'm ok with this as long as tests works.

**Comment by marcusnaslund** [comment]
Yes, all methods that were needed were moved verbatim to `ArrayList`.

**Comment by marcusnaslund** [comment]
@emilwestergren @christopherlagerhult - the old `List` class is now gone.

**Pull request merged**
