### PR TITLE
Write test

### PR DESCRIPTION
**Pull request by davidpiuva**
Testing writing of text on the GPU.

### CODE REVIEW

**Comment by marcusnaslund** [comment]
#1650 is merged

**Comment by davidpiuva** [comment]
Rebased.

**Comment by davidpiuva** [comment]
@emilwestergren Peer review?

**Comment by emilwestergren** [comment]
Have you checked the test for memory leaks?

**Comment by davidpiuva** [comment]
It has 4 `:=` and 4 `free` but I have not modified any script to assert it.

**Comment by emilwestergren** [comment]
You can run `./test.sh base/Profile -x && ./tools/memcheck.sh`

**Comment by davidpiuva** [comment]
I tried from ooc-kean with no luck.
```
error Module not found in sourcepath ./test/base/ProfileTest
use tests
```

**Comment by davidpiuva** [comment]
Done

**Comment by sebastianbaginski** [comment]
Nice font btw. :)

**Pull request merged**
