### PR TITLE
VS Code integration

### PR DESCRIPTION
**Pull request by thomasfanell**
After this functionality is implemented in magic, the following tasks will be supported directly from VS Code:
* build project
* compile current file
* test project
* test current file
* analyze project
* analyze current file

### CODE REVIEW

**Comment by marcusnaslund** [comment]
> After this functionality is implemented in magic

When will that be?

**Comment by thomasfanell** [comment]
@marcusnaslund not too long. The basic functionality will probably be in place during this week, if no unforeseen problems occur.

**Comment by thomasfanell** [comment]
@marcusnaslund is there a task you would like to see in this list?

**Comment by sebastianbaginski** [comment]
@thomasfanell what is `analyze project / file` ?

**Comment by thomasfanell** [comment]
@sebastianbaginski code analysis, project wide or the currently opened file

**Comment by sebastianbaginski** [comment]
Alright, so something like `count lines, methods, % of comments etc.` or more like `static code analysis for possible logic / syntax errors` ? It'd be nice to have either of them :)

**Comment by thomasfanell** [comment]
Code metrics analysis is a nice idea, but initially it will only be style analysis.

**Comment by marcusnaslund** [comment]
Should this wait until `magic` is ready for it? Otherwise I guess this breaks the ability to compile tests from `VSCode`? (Although I don't know if anyone does it right now...?)

**Comment by thomasfanell** [comment]
Yes, this should wait. One could execute the tasks, but magic would not recognize the commands.

**Comment by thomasfanell** [comment]
I'll flag for a peer review when I have basic functionality up and running

**Comment by marcusnaslund** [comment]
Excellent.

**Comment by marcusnaslund** [comment]
> The basic functionality will probably be in place during this week

I guess we jinxed it. :)

**Comment by thomasfanell** [comment]
It needs to work with PRInt too, which delayed it slightly.

**Comment by sebastianbaginski** [comment]
@thomasfanell do you think you could integrate CppCheck (http://cppcheck.sourceforge.net/) at some point ? It could be nice to run even basic static analysis on the rock output.

**Comment by thomasfanell** [comment]
@sebastianbaginski I will add it to the list, good idea!

**Comment by marcusnaslund** [comment]
Sorry, I'm closing this so as to avoid having `PRInt` go through it every time I restart it (which has been a lot recently). Once you're making progress again, feel free to reopen it.

**Comment by sebastianbaginski** [comment]
@marcusnaslund @jonathanudd Could we have a `ignore` label which would cause PRInt skip the labelled PR ?

**Pull request closed without merging**
