### PR TITLE
fixed android build with the other compiler

### PR DESCRIPTION
**Pull request by sebastianbaginski**
Doesn't seem to like `const`.
@marcusnaslund

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Putting the green flag yourself? You're quite a rebel.

**Comment by sebastianbaginski** [comment]
I think the obvious PRs should go straight to you, which means green flag from the start ?

**Comment by marcusnaslund** [comment]
> which means green flag from the start ?

Sure :) But you've usually put the peer review flag there even though you tagged me.

**Comment by sebastianbaginski** [comment]
PRInt seems to be missing some files.

**Comment by marcusnaslund** [comment]
Oops.

**Pull request merged**
