### PR TITLE
Create override fix

### PR DESCRIPTION
**Pull request by emilwestergren**
Still looks like we have missing `override` in the code base. This is not good.

@marcusnaslund peer

### CODE REVIEW

**Comment by marcusnaslund** [comment]
@fredrikbryntesson ?

**Comment by sebastianbaginski** [comment]
Wasn't rock supposed to detect it ?

**Comment by fredrikbryntesson** [comment]
Yes it is supposed to do that. I look into it now why these methods behave so different.

**Comment by marcusnaslund** [comment]
Well, this should be here, so I'm merging.

**Pull request merged**
