### PR TITLE
free leaked error message from stb wrapper

### PR DESCRIPTION
**Pull request by sebastianbaginski**
@marcusnaslund

### CODE REVIEW

**Comment by marcusnaslund** [comment]
What? We have to do this?

**Comment by marcusnaslund** [comment]
What if we hide the `raise` call in an if statement?

**Comment by sebastianbaginski** [comment]
Yes, parameters are always evaluated. If statement would fix this too.

**Comment by marcusnaslund** [comment]
I vote for an if-statement then.

**Comment by sebastianbaginski** [comment]
I mean, it would leak only in case of exception.

**Comment by sebastianbaginski** [comment]
... which would create a leak in this test
```ooc
this add("Test file not found", func {
			try {
				image := RasterRgba open("nonExistingFile")
				expect(false) // Unreachable code since we are expecting an exception
				expect(image, is Null)
			} catch (e: Exception) {
				expect(e message contains("Failed to load image: "))
			}
		})
```

**Comment by marcusnaslund** [comment]
Can't we do something like `e message free()` or whatever in the test?

**Comment by marcusnaslund** [comment]
I don't like adding extra memory management code to free things for events that shouldn't happen.

**Comment by sebastianbaginski** [comment]
ok, updated

**Comment by marcusnaslund** [comment]
Thanks.

**Pull request merged**
