### PR TITLE
Added point+vector arithmetic in 3D

### PR DESCRIPTION
**Pull request by marcusnaslund**
This was possible in 2D, but not in 3D. Will be useful in the other project. Peer review @bettinaselig ?

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Vector + Point = Vector, which doesn't make a lot of sense to me, but it's the same way in 2D.

**Comment by bettinaselig** [comment]
Do you need that for our project?

**Comment by bettinaselig** [comment]
It's a bit strange as you say, but if you need that I don't mind :-)

**Comment by marcusnaslund** [comment]
> Do you need that for our project?

Yes, exactly. :)

**Pull request merged**
