### PR TITLE
Renamed GpuSurface file to GpuCanvas.

### PR DESCRIPTION
**Pull request by davidpiuva**
Builds on https://github.com/magic-lang/ooc-kean/pull/1317

### CODE REVIEW

**Comment by davidpiuva** [comment]
@sebastianbaginski Peer review?

**Comment by sebastianbaginski** [comment]
This one is even smaller than previous, but if you look at the diff directly ... This is funny that each commit has no more than 20 lines changed but more than 300 when combined :)

**Comment by davidpiuva** [comment]
Someone should really make a manual rename tool for Git.

**Comment by marcusnaslund** [comment]
This should not advance to final review until *after* the PR it builds upon has actually been merged and this has been rebased.

**Comment by marcusnaslund** [comment]
#1317 is now merged. This has conflicts.

**Comment by davidpiuva** [comment]
That was the one that i saved for later rebasing to avoid overwriting someones changes.

**Comment by marcusnaslund** [comment]
> That was the one that i saved for later rebasing to avoid overwriting someones changes.

Yes, that's a good idea, just letting you know. :)

**Comment by davidpiuva** [comment]
Replaced by https://github.com/magic-lang/ooc-kean/pull/1332

**Pull request closed without merging**
