### PR TITLE
Moved EGLRgba recycling HOTFIX

### PR DESCRIPTION
**Pull request by emilwestergren**
Hotfix for 2.5.1
Solved memory leaks for EGLImages.
@erikhagglund peer review

### CODE REVIEW

**Comment by erikhagglund** [comment]
Perhaps you should mention what the hotfix solves and which the original pull requests are?

**Comment by erikhagglund** [comment]
As long as it is a simple cherry-pick i do not see any problems with it.

**Comment by marcusnaslund** [comment]
I'm not sure PRInt can handle PR to a release branch, so if you've tested this well I can merge this right away.

**Comment by marcusnaslund** [comment]
Well whatdoyouknow, PRInt didn't blow up... yet.

**Comment by marcusnaslund** [comment]
Ahh but it did now.

**Pull request merged**
