### PR TITLE
Added half gaussian kernel.

### PR DESCRIPTION
**Pull request by niklasborwell**

### CODE REVIEW

**Comment by niklasborwell** [comment]
Pretty sure the test fail here isn't because of this..

**Comment by marcusnaslund** [comment]
No you're fine. But please add a unit test for the function you added.

**Comment by marcusnaslund** [comment]
@niklasborwell

**Comment by niklasborwell** [comment]
Updated with test.

**Comment by marcusnaslund** [comment]
*(gentle reminder)* Please verify that PRInt and a peer reviewer approves before setting the ready label.

**Comment by niklasborwell** [comment]
DOH!

**Comment by niklasborwell** [comment]
But since you already started reviewing I assumed you don't care about a peer review. It's a really small basic addition.

**Comment by marcusnaslund** [comment]
It's OK, but I want to get people used to the new system as quickly as possible.

**Comment by marcusnaslund** [comment]
that's the way you do it :sunglasses:

**Pull request merged**
