### PR TITLE
Set pointer to array data to null after free

### PR DESCRIPTION
**Pull request by thomasfanell**
@sebastianbaginski

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
Do you want to have this always or just in the "safe" version ? Do we clear the memory of other objects after freeing them ? What's the motivation here ?

**Comment by marcusnaslund** [comment]
> Do we clear the memory of other objects after freeing them

We do, especially in the other project (`if (object) { object free(); object = null }`).

**Comment by sebastianbaginski** [comment]
Sure, but I mean automatically like this. Don't get me wrong, I think it's ok.

**Comment by thomasfanell** [comment]
Why would we ever want dangling pointers to array data?

**Comment by sebastianbaginski** [comment]
I mean from the user's point of view there is no difference between
```
object := Object new()
object free() // garbage now
object free() // crash

array := Int[10] new()
array free() // set to null
array free() // no crash
```

But I get it now after your "private" argument :)

**Comment by marcusnaslund** [comment]
I'm sorry to say this broke the android build with `-DfastCv` flag. :(
I don't know if @sebastianbaginski has an easy fix, otherwise I will revert this before today's code freeze and we'll make a new shot it next week.

**Comment by thomasfanell** [comment]
How is that even possible?

**Comment by thomasfanell** [comment]
Let's revert and look at it... better to be safe than sorry

**Pull request merged**
