### PR TITLE
Fixes for issue #1278

### PR DESCRIPTION
**Pull request by thomasfanell**
**This PR depends on upcoming `rock 1.0.16` - do not merge before verifying that everyone has updated.**
- [x]  `hasNext?`
- [x]  `hasPrev?`
- [x]  `inheritsFrom?`
- [x]  `instanceOf?`
- [x]  rename `hasPrev` to `hasPrevious`
- [x]  remove files in `system/lang/` and put them in `system` root instead
- [ ]  generate more readable C code (unlikely in this PR)

### CODE REVIEW

**Comment by thomasfanell** [comment]
Task one of #1278 fixed.

**Comment by marcusnaslund** [comment]
Awesome.

**Comment by marcusnaslund** [comment]
> do not merge before verifying that everyone has updated.

It's not even that simple. If people get the new rock *before*, they won't be able to compile the version of this repo that they have. We will have to do it all simultaneously.

**Comment by thomasfanell** [comment]
A family event!

**Comment by marcusnaslund** [comment]
Let me know when the new rock version is finished (no rush if you want to do some of the other points on that issue as well), and this party is a go.

**Comment by thomasfanell** [comment]
Will do!

**Comment by marcusnaslund** [comment]
Also, remember to make a corresponding PR in the other project.

**Comment by thomasfanell** [comment]
#1278 renamed `sdk` to `system`

**Comment by marcusnaslund** [comment]
`/giphy celebrate`

**Comment by marcusnaslund** [comment]
Conflicts.

**Comment by thomasfanell** [comment]
@marcusnaslund let me know when you're ready to peer review, I'll fix the conflicts then.

**Pull request merged**
