### PR TITLE
Reinitialize string literals mutex if needed

### PR DESCRIPTION
**Pull request by thomasfanell**
@sebastianbaginski

### CODE REVIEW

**Comment by thomasfanell** [comment]
Hang on, this became a mess...

**Comment by thomasfanell** [comment]
Let's pretend this went smoothly...

**Comment by marcusnaslund** [comment]
This is a perfect case for "squash all my commits into one"

**Comment by thomasfanell** [comment]
On the agenda, I was waiting for PRint

**Pull request merged**
