### PR TITLE
Normalized input to quaternion SLERP

### PR DESCRIPTION
**Pull request by tomasmahlberg**
This requires the input quaternions to be normalized. We want to be on the safe side here and always do this, as this has caused some unexpected problems when any of the inputs has been "almost normalized".

### CODE REVIEW

**Comment by tomasmahlberg** [comment]
@niklasborwell review?

**Comment by marcusnaslund** [comment]
Requires some updated tests

**Comment by marcusnaslund** [comment]
`FloatRotation3D ....f.. failed -> sphericalLinearInterpolation : expected equal to 0.21 was 0.21 [tolerance: 0.00010000]`

**Comment by tomasmahlberg** [comment]
Oops, missed that one. Fixed now. As a side note, we're planning to get rid of that meaningless wrapper class at some point.

**Comment by marcusnaslund** [comment]
Sounds good to me

**Pull request merged**
