### PR TITLE
merged ThreadLocal classes for unix and windows

### PR DESCRIPTION
**Pull request by sebastianbaginski**
The only difference was the function used to get current thread id.
@marcusnaslund

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
I'm not so sure we should even use this class. Thread ID is not guaranted to be unique through the application lifetime, at least in pthreads. When thread is done, its ID can be reused when creating next thread, which makes this class unreliable in my opinion.

**Comment by marcusnaslund** [comment]
If you want to throw it out completely, fine by me.

**Comment by marcusnaslund** [comment]
It's the one thing that stops us moving `system/threading` out to `concurrent`.

**Comment by sebastianbaginski** [comment]
Maybe let's start with this and we can talk about it next week, I gotta go soon.

**Pull request merged**
