### PR TITLE
Added suppression file and updated memcheck script

### PR DESCRIPTION
**Pull request by marcusnaslund**
Copied from some other mysterious project.

I would also like to (for the time being) suppress everything related to the `Raster` classes but not the `RasterTest` itself but I don't yet know how to do that. @sebastianbaginski probably does?

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
You can use regular expressions in suppression file.

**Comment by marcusnaslund** [comment]
> You can use regular expressions in suppression file.

Thank you. And thank you valgrind.

**Comment by marcusnaslund** [comment]
Changed my mind. This is allowed to leak (for now), so let's not suppress anything extra.
Peer review @fredrikbryntesson ?

**Comment by fredrikbryntesson** [comment]
I thought we suppressed more stuff actually.

**Comment by fredrikbryntesson** [comment]
But looks good.

**Comment by marcusnaslund** [comment]
> I thought we suppressed more stuff actually.

I recently removed two entries. :) I will examine how hard it is to remove the String suppression after my upcoming trip to a certain warm country.

**Pull request merged**
