### PR TITLE
test for binary search with covers

### PR DESCRIPTION
**Pull request by sebastianbaginski**
I had some weird problems yesterday when trying to use it on a vector list with covers, in the other project. Seems to work fine here though.
@marcusnaslund review

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Have you run `memcheck.sh` to make sure there are no invalid read/writes etc. going on?

**Comment by sebastianbaginski** [comment]
valgrind does not report any problems.

**Comment by sebastianbaginski** [comment]
@marcusnaslund updated `upperBound`

**Comment by marcusnaslund** [comment]
Great, thanks.

**Pull request merged**
