### PR TITLE
Remove bgr

### PR DESCRIPTION
**Pull request by davidpiuva**
Removing BGR completely. This final step breaks backward compatibility to prevent anyone from creating new dependencies to the BGR weirdness.

### CODE REVIEW

**Comment by davidpiuva** [comment]
Tests fails now because there is no branch with the same name in the other repository.

**Comment by davidpiuva** [comment]
@thomasfanell Peer review?

**Comment by thomasfanell** [comment]
Looks good to me

**Comment by marcusnaslund** [comment]
Good job.

**Pull request merged**
