### PR TITLE
Now prints name of tests that fails with exception.

### PR DESCRIPTION
**Pull request by emilwestergren**
Can't believe no one did this before...
@marcusnaslund

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Is it working? I don't see any difference when trying to break tests.
Also, would this mean a failing test wouldn't print a stack trace? Because that might be something we want.

**Comment by emilwestergren** [comment]
It worked for me locally, I can try again. I guess I can just re-throw the exception if you want a stack trace

**Comment by emilwestergren** [comment]
I think with the old solution, unhandled exceptions just failed the test, i.e. no stack trace so this should be an improvement.

**Comment by emilwestergren** [comment]
For example, adding this somewhere in the tested code:
```ooc
OutOfMemoryException new() throw()
```
Fails with:
09:38:55 BlockedQueue 'cover' failed with unhandled exception 
[OutOfMemoryException]: Failed to allocate more memory!
(SIGABRT) abort program
[fancy backtrace]
0     BacktraceHandler backtrace()             in Backtrace  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Backtrace.ooc:26)           
1     Exception getCurrentBacktrace()          in Exception  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Exception.ooc:167)          
2     _signalHandler()                         in Exception  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Exception.ooc:231)          
3     killpg()                                 in            (at (null):0)                                                                          
4     GI raise()                               in            (at /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56)
5     GI abort()                               in            (at /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91)                                
6     Exception throw()                        in Exception  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Exception.ooc:157)          
7     Fixture run()                            in Fixture    (at /home/ewestergren/versioned/ooc/ooc-kean/source/unit/Fixture.ooc:52)               
8     test_concurrent_BlockedQueueTest_load()  in            (at /home/ewestergren/versioned/ooc/ooc-kean/test/concurrent/BlockedQueueTest.ooc:97)  
9     _test_Tests_load()                       in            (at /home/ewestergren/versioned/ooc/ooc-kean/rock_tmp/ooc/tests/./test/Tests.c:90)     
10    main()                                   in            (at /home/ewestergren/versioned/ooc/ooc-kean/./test/Tests.ooc:13)                      
11    libc_start_main()                        in            (at /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321)                             
12    _start()                                 in            (at (null):0)

**Comment by sebastianbaginski** [comment]
I think this is great :+1:

**Comment by emilwestergren** [comment]
Currently, it fails like this:

09:40:12 BlockedQueue ff failed
09:40:12 WorkerThread f. failed
09:40:12 SynchronizedQueue ..... done in 0.14s
09:40:12 ThreadPool fffff failed
09:40:12 SynchronizedList ....................... done in 0.64s
09:40:13 Thread .... done in 1.81s
09:40:15 RecycleBin . done
09:40:15 Promise ......f failed in 1.02s
09:40:16 WaitLock .... done
Total time: 3.66 s
Failed tests: 4 [BlockedQueue, WorkerThread, ThreadPool, Promise]

**Comment by marcusnaslund** [comment]
Sure, but how often do we explicitly throw exceptions? If you do something like
```ooc
a: VectorList<Int> //uninitialized
a add(3)
```
you'll crash and get segfaults in both versions without any difference (as far as I could tell this morning).

**Comment by emilwestergren** [comment]
Yes, that won't make a difference, but there are a lot of cases where we can throw exceptions. Will `raise` throw ooc exception or simply abort? In that case maybe `Debug error` should throw an exception instead.

**Comment by marcusnaslund** [comment]
Raise is just a shorthand for throwing a new exception:

```ooc
raise: func ~withClass (message: String, origin: Class = null) { Exception new(origin, message) throw() }
```

But it looks like stuff like double-free or uninitialized memory works in a different way... @thomasfanell ?

**Comment by emilwestergren** [comment]
So what is the status here?

**Comment by marcusnaslund** [comment]
Well there's no problem here, but I don't quite see what problems (in our current code base) you're actually solving here.

**Comment by emilwestergren** [comment]
Check my example above.

**Comment by marcusnaslund** [comment]
"In our current codebase". We don't throw any `OutOfMemoryException`s, or really any exceptions. Do we want to? That's a very different style from before, and keep in mind they're not at all thread-safe.

**Comment by emilwestergren** [comment]
We do because of all the `Debug error()` calls, this fix will now print which test caused the error.

**Comment by emilwestergren** [comment]
```
09:22:23 FloatBox2D .....................DISTANCE
[Exception]: DISTANCE
(SIGABRT) abort program
[fancy backtrace]
0     BacktraceHandler backtrace()         in Backtrace  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Backtrace.ooc:26)           
1     Exception getCurrentBacktrace()      in Exception  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Exception.ooc:167)          
2     _signalHandler()                     in Exception  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Exception.ooc:231)          
3     killpg()                             in            (at (null):0)                                                                          
4     GI raise()                           in            (at /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56)
5     GI abort()                           in            (at /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91)                                
6     Exception throw()                    in Exception  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Exception.ooc:157)          
7     Exception rethrow()                  in Exception  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Exception.ooc:163)          
8     Fixture run()                        in Fixture    (at /home/ewestergren/versioned/ooc/ooc-kean/source/unit/Fixture.ooc:48)               
9     test_geometry_FloatBox2DTest_load()  in            (at /home/ewestergren/versioned/ooc/ooc-kean/test/geometry/FloatBox2DTest.ooc:234)     
10    _test_Tests_load()                   in            (at /home/ewestergren/versioned/ooc/ooc-kean/rock_tmp/ooc/tests/./test/Tests.c:101)    
11    main()                               in            (at /home/ewestergren/versioned/ooc/ooc-kean/./test/Tests.ooc:13)                      
12    libc_start_main()                    in            (at /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321)                             
13    _start()                             in            (at (null):0)       
```
VS

```
09:23:03 FloatBox2D .....................DISTANCE
'box to point distance' failed with unhandled exception 
[Exception]: DISTANCE
(SIGABRT) abort program
[fancy backtrace]
0     BacktraceHandler backtrace()         in Backtrace  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Backtrace.ooc:26)           
1     Exception getCurrentBacktrace()      in Exception  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Exception.ooc:167)          
2     _signalHandler()                     in Exception  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Exception.ooc:231)          
3     killpg()                             in            (at (null):0)                                                                          
4     GI raise()                           in            (at /build/eglibc-oGUzwX/eglibc-2.19/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:56)
5     GI abort()                           in            (at /build/eglibc-oGUzwX/eglibc-2.19/stdlib/abort.c:91)                                
6     Exception throw()                    in Exception  (at /home/ewestergren/versioned/ooc/ooc-kean/source/system/Exception.ooc:157)          
7     Fixture run()                        in Fixture    (at /home/ewestergren/versioned/ooc/ooc-kean/source/unit/Fixture.ooc:52)               
8     test_geometry_FloatBox2DTest_load()  in            (at /home/ewestergren/versioned/ooc/ooc-kean/test/geometry/FloatBox2DTest.ooc:234)     
9     _test_Tests_load()                   in            (at /home/ewestergren/versioned/ooc/ooc-kean/rock_tmp/ooc/tests/./test/Tests.c:101)    
10    main()                               in            (at /home/ewestergren/versioned/ooc/ooc-kean/./test/Tests.ooc:13)                      
11    libc_start_main()                    in            (at /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321)                             
12    _start()                             in            (at (null):0)   
```

**Comment by marcusnaslund** [comment]
That's what I wanted to hear. :beers:

**Pull request merged**
