### PR TITLE
Fixed some small issues in stb_image

### PR DESCRIPTION
**Pull request by sebastianbaginski**
- possible out of bounds reads
- unchecked error codes from `fseek`
- possible uninitialized array reads

@marcusnaslund

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Looks like the repo this file comes from is undergoing some continous development, should we look at also updating our version with what's new? @emilwestergren @tomasmahlberg

**Comment by marcusnaslund** [comment]
It might be a better idea would be to make this PR to the [original repo](https://github.com/nothings/stb) directly, and then take *that* latest version and merge it here.

**Comment by sebastianbaginski** [comment]
It may or may not be accepted in the original repo, I don't think it is worth waiting, it's a very simple fix. I'd say let's just fix it ourselves here **and** make a pull request to stb repo. Merging this won't be a big problem later, eventually.

**Comment by marcusnaslund** [comment]
If we care about updating, we should at least do that *before* this change. Input @fredrikbryntesson ?

**Comment by sebastianbaginski** [comment]
It is not so easy as simply replacing the files with new versions. Looks like the part of `stbi` library we are interested in became header-only. Trying to replace the headers with new version will cause compiler failure related to multiple definitions of functions from the stbi header. Not mentioning hundreds of warnings when compiling with -Wall, which we probably have to fix ourselves.
My suggestion is to merge this, and create an issue about updating the stbi library, I can do that later.

**Comment by sebastianbaginski** [comment]
https://github.com/magic-lang/ooc-kean/issues/1240

**Comment by fredrikbryntesson** [comment]
Depressing :( but okay. If updating causes too much work it is better to merge our patch with our current version of stb_image. Do the pull request to upstream anyway but maybe it will not be of any use for us because of their new version is so much different from the one we are currently using?

**Comment by sebastianbaginski** [comment]
@fredrikbryntesson : the file we have patched here is gone from stbi :)
Of course the functions are still there, but inlined in the header file.

**Comment by fredrikbryntesson** [comment]
Ok, then I guess it is not so much more to do. But I guess checking if an update is possible or what they have improved should be done in somewhat near future.

**Comment by marcusnaslund** [comment]
I will merge this, and we will discuss what to do with `stb_image` later. Good you made the issue.

**Comment by sebastianbaginski** [comment]
OK, thanks. I think there will be more small fixes soon, I will take care of updating stbi & merging them next week.

**Pull request merged**
