### PR TITLE
Assert for YuvOptimized support on init

### PR DESCRIPTION
**Pull request by christopherlagerhult**

### CODE REVIEW

**Comment by marcusnaslund** [comment]
ping @thomasfanell for the c++ port

**Comment by thomasfanell** [comment]
Copy that.

**Comment by thomasfanell** [comment]
Ping @marcusnaslund

**Comment by marcusnaslund** [comment]
...yes? :)

**Comment by thomasfanell** [comment]
Merge? :-)

**Comment by marcusnaslund** [comment]
@christopherlagerhult `ready`?

**Comment by christopherlagerhult** [comment]
I have been waiting for PRint. Other than that its ready

**Comment by marcusnaslund** [comment]
PRInt was ready and it restarted for some reason

**Pull request merged**
