### PR TITLE
Added support for high-priority geometry covers in Fixture

### PR DESCRIPTION
**Pull request by marcusnaslund**
Depends on #1505 

After this we can check all the high-priority items in #1500

### CODE REVIEW

**Comment by marcusnaslund** [comment]
@niklasborwell I'm not sure how to apply `within()` for `FloatEuclidTransform` or `FloatTransform2D`/`3D`. Do we need it or is it enough to compare with `equal to()` which uses the `==` operators for these classes?

**Comment by niklasborwell** [comment]
It will still use a proper float comparison, right? Like less than some default threshold

**Comment by marcusnaslund** [comment]
It will use whatever the `==` operators use, which at this moment mostly is *not* proper float comparison. We should probably change that, right?

**Comment by niklasborwell** [comment]
Ok, I see. Yes, definitely. But I thought the == operator would be changed? When would you ever not want to use the proper version?

**Comment by marcusnaslund** [comment]
It should be, but it hasn't. I will make an issue and fix it.

**Comment by marcusnaslund** [comment]
#1516

**Comment by marcusnaslund** [comment]
Peer review @sebastianbaginski ? :)

**Comment by sebastianbaginski** [comment]
ok

**Comment by sebastianbaginski** [comment]
Generic programming does not exist in ooc and this pull request proves it.

**Comment by sebastianbaginski** [comment]
Of course not your fault @marcusnaslund , you did the best you could here :)

**Pull request merged**
