### PR TITLE
added toNanoseconds function

### PR DESCRIPTION
**Pull request by thomasfanell**
@emilwestergren

### CODE REVIEW

**Comment by marcusnaslund** [comment]
I will just take the flag off to not confuse myself. This PR is ready, just needs some fixes in PRInt.

**Comment by thomasfanell** [comment]
ok

**Comment by marcusnaslund** [comment]
Taking it off final review again until corresponding branch is fixed.

**Comment by marcusnaslund** [comment]
PRInt fails because of a corresponding branch, but it will not be merged.

**Pull request merged**
