### PR TITLE
Primary feature1.1

### PR DESCRIPTION
**Pull request by emilwestergren**
Necessary changes for release of primary feature 1.1

@marcusnaslund peer review

### CODE REVIEW

**Comment by marcusnaslund** [comment]
PRInt fails, but I think that's a bug in PRInt, and I think @fredrikbryntesson is on it.

**Comment by marcusnaslund** [comment]
Otherwise, approved.

**Comment by fredrikbryntesson** [comment]
Temporary close

**Comment by marcusnaslund** [comment]
Can we confirm all commits are present here?

**Comment by emilwestergren** [comment]
Yes, confirmed.

**Pull request merged**
