### PR TITLE
Renamed GpuSurface class to GpuCanvas.

### PR DESCRIPTION
**Pull request by davidpiuva**
Builds on https://github.com/magic-lang/ooc-kean/pull/1325

### CODE REVIEW

**Comment by davidpiuva** [comment]
@sebastianbaginski Peer review?

**Comment by davidpiuva** [comment]
You can look at the last commit in each PR.

**Comment by sebastianbaginski** [comment]
Looks OK.

**Comment by marcusnaslund** [comment]
This should not advance to final review until *after* the PR it builds upon has actually been merged and this has been rebased.

Sorry, it's just that I spend most of my days staring at the PR list, and it's easier this way.

**Comment by sebastianbaginski** [comment]
>  I spend most of my days staring at the PR list, and it's easier this way.

We could have another flag for PRs which `depends on` other ones.

**Comment by marcusnaslund** [comment]
> We could have another flag for PRs which depends on other ones.

No the point is, if a PR depends on another, it is still subject to change as the other PR might need revisioning. Thus review should wait until after. Of course, asking someone else to look through it and make an informal peer review, so it'll hopefully be smooth and fast later, can be a good idea.

**Comment by davidpiuva** [comment]
Just changing the name of a class reveals an old bug that was not detected before and prevents any compilation.

**Comment by davidpiuva** [comment]
Runs again after rebase.

**Comment by sebastianbaginski** [comment]
It looks OK. I'm setting green flag assuming that this PR does not have any dependencies (as https://github.com/magic-lang/ooc-kean/pull/1314 is closed).

**Comment by davidpiuva** [comment]
I made a new pull request for that one. https://github.com/magic-lang/ooc-kean/pull/1325

**Pull request merged**
