### PR TITLE
Removed more Text usage

### PR DESCRIPTION
**Pull request by marcusnaslund**
- Removed `Text` support in `Numbers` and `HashMap`.
- Adapted `PromiseTest` and `ThreadPoolTest` to return `String` rather than `Text`.
- Removed `test/unit/TextTest.ooc` (there is still a `TextTest` in `test/system`).
- Removed `Text` support from `Fixture` and `Cell`.
- Removed `raise` overloads for `Text`.

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Peer review @sebastianbaginski ?

**Comment by marcusnaslund** [comment]
*fast*

**Comment by sebastianbaginski** [comment]
Nah, 3 minutes for changes that are mostly deletes, seems reasonable. Besides, we all _trust_ your code.

**Comment by marcusnaslund** [comment]
I included the time it takes to tag you until I get a response. :)

**Pull request merged**
