### PR TITLE
Now using custom vertex shader when drawing lines.

### PR DESCRIPTION
**Pull request by emilwestergren**
Drawing lines now works. @christopherlagerhult

### CODE REVIEW

**Comment by christopherlagerhult** [comment]
I should probably add a version flag for my new libs.

**Comment by emilwestergren** [comment]
It works on the other starfish at least, haven't tested on eagle

**Comment by christopherlagerhult** [comment]
Tested it and it works for eagle

**Comment by marcusnaslund** [comment]
There should be no review flags for the starfish branch right?

**Comment by emilwestergren** [comment]
Should I close this @christopherlagerhult ?

**Comment by christopherlagerhult** [comment]
I guess I can add this by rebasing so yes

**Pull request closed without merging**
