### PR TITLE
static File remove method

### PR DESCRIPTION
**Pull request by sebastianbaginski**
@marcusnaslund

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Haha. You're too fast for me.

**Comment by marcusnaslund** [comment]
But while you're at it - are there any other static methods like this we need?

**Comment by marcusnaslund** [comment]
Also - I expect a test for the function.

**Comment by sebastianbaginski** [comment]
I think not now, but maybe `copy`, `exists` and `rename` ?

**Comment by marcusnaslund** [comment]
Sounds good to me. Something like `exists` already exists (heh), I believe.

**Comment by sebastianbaginski** [comment]
Updated with test.

**Pull request merged**
