### PR TITLE
Merge primaryFeature1.8

### PR DESCRIPTION
**Pull request by tomasmahlberg**

### CODE REVIEW

**Comment by tomasmahlberg** [comment]
So... any ideas about this failed test?

**Comment by tomasmahlberg** [comment]
Oh wait, we should just ignore those parts of the test for now.

**Comment by marcusnaslund** [comment]
Exactly. Very few things have changed here, so get someone to approve.

**Comment by tomasmahlberg** [comment]
@niklasborwell Can you give this a green flag?

**Pull request merged**
