### PR TITLE
Merged develop.

### PR DESCRIPTION
**Pull request by emilwestergren**
@marcusnaslund peer review

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Looks good.

**Comment by emilwestergren** [comment]
I think Print fails because it doesn't use the correct version of the wrapper.

**Comment by marcusnaslund** [comment]
Hm, but if it used the wrong wrapper, PRs to this branch would have failed before too... @fredrikbryntesson ?

**Comment by emilwestergren** [comment]
Yeah, it's the correct wrapper but for some reason it can't find the shared library.

**Comment by emilwestergren** [comment]
Still fails with same error.

**Comment by marcusnaslund** [comment]
Works now.

**Pull request merged**
