### PR TITLE
Renamed _PromiseState to TaskState

### LINKED ISSUE #1889: Rename _PromiseState

### PR DESCRIPTION
**Pull request by marcusnaslund**
The name was confusing since it was also used in `_ThreadFuture<T>` and `Task`.

Also removed the `_` since it's used in multiple classes - we cannot really consider it "private".

Fixes #1889

### CODE REVIEW

**Comment by marcusnaslund** [comment]
OK with you @emilwestergren ?

**Comment by emilwestergren** [comment]
I think it's still confusing that we have a class `Task`, a state called `TaskState`, and this state is also used in `Promise` which neither is a task or holds a task.

**Comment by marcusnaslund** [comment]
Maybe we should move `Task` out of `ThreadPool` into its own class, and use `Task` internally for `_ThreadPromise` and `_ThreadFuture`?

**Comment by emilwestergren** [comment]
I don't know, it's clear these classes need some refactoring.

**Comment by marcusnaslund** [comment]
Yeah.. let me get back to this when I have some more time.

**Pull request closed without merging**
