### PR TITLE
fixed possible out of bounds access in stbi

### PR DESCRIPTION
**Pull request by sebastianbaginski**
@marcusnaslund

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Might be a nice gesture to make a similar PR to upstream.

**Comment by sebastianbaginski** [comment]
I'm not really sure if this is even possible, more like super defensive programming.
But on the other hand, it is not so easy to follow the control flow in this code, this fix might be legit.

**Comment by fredrikbryntesson** [comment]
The upstream version are not working at all for us now?

**Comment by sebastianbaginski** [comment]
It is working. This is to make Coverity happy

**Comment by fredrikbryntesson** [comment]
Ok but it is possible to make upstream Coverity friendly?

**Comment by fredrikbryntesson** [comment]
Or is this a dead end?

**Comment by sebastianbaginski** [comment]
Making Coverity happy is a continuous process :)

**Comment by fredrikbryntesson** [comment]
So try to push it upstream, it would be better in the end.

**Comment by sebastianbaginski** [comment]
OK, first lets merge it here and see if it really fixes the problem.

**Comment by marcusnaslund** [comment]
There is no problem?

**Comment by sebastianbaginski** [comment]
Analysis tool complains that `z->idata + ioff` can exceed the valid memory range.

**Comment by marcusnaslund** [comment]
Right, but it doesn't actually happen to us as far as we know?

**Comment by sebastianbaginski** [comment]
I don't think so.

**Comment by marcusnaslund** [comment]
This only failed because `SynchronizedTest` segfaulted, unfortunately I didn't have time to merge the (hopefully) fix before this. So this goes in.

**Pull request merged**
