### PR TITLE
Added equal to() support for remaining geometry+math types

### LINKED ISSUE #1500: Add support for comparing relevant classes in unit test framework.
We need to be able to use the `is equal to` framework with all relevant classes.

Higher priority, i.e. used a lot:
- [x] FloatVector2D
- [x] FloatVector3D
- [x] FloatPoint2D
- [x] FloatPoint3D
- [x] Quaternion
- [x] FloatEuclidTransform
- [x] FloatRotation3D
- [x] FloatTransform2D
- [x] FloatTransform3D

Lower priority:
- [ ] FloatBox2D
- [ ] FloatConvexHull2D
- [ ] FloatShell2D
- [ ] IntBox2D
- [x] IntPoint2D
- [x] IntPoint3D
- [ ] IntShell2D
- [ ] IntTransform2D
- [x] IntVector2D
- [x] IntVector3D
- [ ] FloatComplex
- [ ] FloatMatrix

### PR DESCRIPTION
**Pull request by marcusnaslund**
Depends on #1510 and #1517 

Fixes #1500 by adding support for the remaining seven types.

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Peer review @sebastianbaginski ?

**Comment by sebastianbaginski** [comment]
OK

**Comment by marcusnaslund** [comment]
I miss those uplifting adjectives.

**Comment by marcusnaslund** [comment]
@niklasborwell All geometry and math covers are now supported, and comparison with `==` is done with proper floating point comparison. Let me know if (when) something of this doesn't work as expected

**Pull request merged**
