### PR TITLE
Adapted for new generic extension functionality in rock 1.0.20

### PR DESCRIPTION
**Pull request by thomasfanell**

### CODE REVIEW

**Comment by marcusnaslund** [comment]
I thought we said everything was compatible with the new version? @fredrikbryntesson

**Comment by fredrikbryntesson** [comment]
That was my impression also.

**Comment by thomasfanell** [comment]
Well, not the generic extension part. We talked about this a few days ago. Earlier today when we discussed this, we were talking about arrays of generic types  (or at least, that was my impression).

**Comment by marcusnaslund** [comment]
I'd prefer postponing everything that requires a code change for the next release then.

**Pull request closed without merging**
