### PR TITLE
Removed BinarySequence reader and writer

### PR DESCRIPTION
**Pull request by marcusnaslund**
We're not using it, and never have, and it's dependent on the "old" I/O files from the original sdk, which we want to rewrite eventually.

For now, it's safe to just remove this.

Objections @sebastianbaginski ?

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
It is great to have such functions ready and tested in the toolbox, I hope they will come back one day.

**Comment by marcusnaslund** [comment]
I could also fix them up a bit and write some basic tests...?

**Comment by sebastianbaginski** [comment]
We do not work so much with data which must not depend on the platform endianess, like portable file formats, network code etc. I'm not sure if we should keep this now.

**Comment by marcusnaslund** [comment]
Then hello, garbage can.

**Pull request merged**
