### PR TITLE
Removed FloatRotation3D wrapper class

### PR DESCRIPTION
**Pull request by tomasmahlberg**

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Why was this class created in the first place? Did it use to do more?

**Comment by tomasmahlberg** [comment]
I'm not sure exactly what the purpose of this class was and no, it never used to do anything more than what it does now. @niklasborwell Any input here?

**Comment by niklasborwell** [comment]
It never had a purpose. Good riddance!

**Comment by tomasmahlberg** [comment]
@niklasborwell

**Pull request merged**
