### PR TITLE
Comparing output - RasterCanvasTest

### PR DESCRIPTION
**Pull request by davidpiuva**
Making comparisons in one of the raster test modules. Test images are moved to the "correct" folder. Generated images generated by the old test may still exist locally until output is cleaned up.

The name "RasterCanvasTest" should probably be changed soon since canvas does not exist and raster will soon be renamed to exclude GPU raster images.

### CODE REVIEW

**Comment by davidpiuva** [comment]
@fredrikbryntesson Peer review?

**Comment by davidpiuva** [comment]
```
==7347== Memcheck, a memory error detector
==7347== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==7347== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==7347== Command: ./Tests -n
==7347== Parent PID: 7346
==7347== 
==7347== 
==7347== HEAP SUMMARY:
==7347==     in use at exit: 664 bytes in 11 blocks
==7347==   total heap usage: 4,198 allocs, 4,187 frees, 59,117,000 bytes allocated
==7347== 
==7347== LEAK SUMMARY:
==7347==    definitely lost: 0 bytes in 0 blocks
==7347==    indirectly lost: 0 bytes in 0 blocks
==7347==      possibly lost: 0 bytes in 0 blocks
==7347==    still reachable: 664 bytes in 11 blocks
==7347==         suppressed: 0 bytes in 0 blocks
==7347== Reachable blocks (those to which a pointer was found) are not shown.
==7347== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==7347== 
==7347== For counts of detected and suppressed errors, rerun with: -v
==7347== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by marcusnaslund** [comment]
This fixes #1442 ?

**Comment by davidpiuva** [comment]
Yes

**Comment by marcusnaslund** [comment]
:tada:

**Pull request merged**
