### PR TITLE
Made one Vector::copy abstract and removed StackVector

### PR DESCRIPTION
**Pull request by marcusnaslund**
This method is never used, and also make little sense (calling `copy()` on a `StackVector` would give you a `HeapVector`). If anything, we could make it abstract and have the actual implementations in each derived class. Comments @sebastianbaginski ?

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
>  we could make it abstract and have the actual implementations in each derived class

This :+1:

**Comment by marcusnaslund** [comment]
I don't really understand this `StackVector` - Why do we have it? We never use it. It seems to me like it's just like `HeapVector` except the constructor takes a backend that's somehow stack-allocated. How can I be sure to allocate on the stack for the copy?

**Comment by sebastianbaginski** [comment]
> How can I be sure to allocate on the stack for the copy?

Stack memory can be allocated with `alloca`, but the memory is freed when the calling function returns, so I think it is not suitable for data structures.

**Comment by marcusnaslund** [comment]
@fredrikbryntesson You appear to have written the `StackVector` class some 15 months ago. :) Can you shed some light on the intended use case?

**Comment by fredrikbryntesson** [comment]
I think it was something that @niklasborwell needed, I do not remember what it was. We never used it.

**Comment by marcusnaslund** [comment]
I feel like we can remove it, then?

**Comment by fredrikbryntesson** [comment]
Kill it, with fire.

**Comment by niklasborwell** [comment]
I don't remember any of this. If it's not used, bin it!

**Comment by marcusnaslund** [comment]
Thank you all. 
Peer review @sebastianbaginski ?

**Comment by marcusnaslund** [comment]
Killed. With considerable amounts of fire.

**Pull request merged**
