### PR TITLE
Added absolute to complex vector list.

### PR DESCRIPTION
**Pull request by niklasborwell**

### CODE REVIEW

**Comment by johannordstroem** [comment]
Should we also make a test for this?

**Comment by marcusnaslund** [comment]
You know, in bridge, `absolute(myList)` works just as well for float and complex types (and double and int and ...)

**Comment by marcusnaslund** [comment]
what's up here?

**Comment by niklasborwell** [comment]
It's just been not prioritized for a while. It's still gonna get merged.

**Pull request merged**
