### PR TITLE
Added function for printing EGL extensions

### PR DESCRIPTION
**Pull request by emilwestergren**
@marcusnaslund peer review

### CODE REVIEW

**Comment by marcusnaslund** [comment]
`error: initialization discards ‘const’`

**Comment by emilwestergren** [comment]
I don't get the error

**Comment by marcusnaslund** [comment]
I think the problem is that the EGL function returns a `const char*`, but in ooc you store it as a `CString` which is a cover of `char*`, and thus ignore the `const` declaration.

Unfortunately the `const` keyword is meaningless in ooc, but I know I solved the same problem a while back, right now I don't remember exactly how but I will take a look.

**Comment by marcusnaslund** [comment]
Oh yeah, look up `CONST_CHAR_CAST` in `draw/gpu/opengl/backend/gles3/external`.

**Comment by emilwestergren** [comment]
Updated

**Comment by marcusnaslund** [comment]
Yep, seems to work now.

**Pull request merged**
