### PR TITLE
Bumped copyright notice from 2016 to 2017

### PR DESCRIPTION
**Pull request by marcusnaslund**
Yay now we have something to release. @fredrikbryntesson

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Or should it be 2016-2017?
Important questions.

**Comment by fredrikbryntesson** [comment]
Hmm I think it should be 2016-2017, or maybe 2014-2017 ?

**Comment by marcusnaslund** [comment]
It was technically not MIT before 2016 though.

**Comment by fredrikbryntesson** [comment]
So 2016-2017 then.

**Comment by marcusnaslund** [comment]
OK now?

**Pull request merged**
