### PR TITLE
Fixed unnecessary canvas allocation when recycling image.

### PR DESCRIPTION
**Pull request by sebastianbaginski**
Cherry picked from primaryFeature1.1 branch.
@marcusnaslund

### CODE REVIEW

**Comment by marcusnaslund** [comment]
I'm afraid #1642 caused conflicts.

**Comment by sebastianbaginski** [comment]
Yeah. What shall we do now ? The idea was to use exactly the same commit in both branches.

**Comment by marcusnaslund** [comment]
Is this absolutely necessary? Can you use the `primaryFeature1.1` branch for tracker tests until friday?

**Comment by sebastianbaginski** [comment]
I guess it can wait. @bettinaselig ?

**Comment by bettinaselig** [comment]
Yes, Marcus and I discussed that already. Thanks, @sebastianbaginski.

**Pull request closed without merging**
