### PR TITLE
fixed datatype in thread local

### PR DESCRIPTION
**Pull request by sebastianbaginski**
@marcusnaslund

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
https://github.com/magic-lang/ooc-kean/issues/1360

**Comment by marcusnaslund** [comment]
This fixes it? Makes no sense.

**Comment by sebastianbaginski** [comment]
Yeah, try it :) it is wrong to use either of these types imho

**Comment by marcusnaslund** [comment]
Right, it works. But, `Long` was the key before as well.. so still makes no sense to me.

**Comment by sebastianbaginski** [comment]
I think it was ULong on linux

**Pull request merged**
