### PR TITLE
Good bye, Text!

### LINKED ISSUE #1724: Remove Text
Yes. 

Since string literals don't leak anymore, and since people are mostly just confused by how `Text` ownership works, there is no need for `Text`. Right now we just have a lot of duplicate code with `toString` and `toText` in tons of classes.

We've also caused a lot of confusion for ourselves, where for example the `filename` arguments to `FileWriter` and `FileReader` are different, one of them expects a `String`, the other a `Text`...

We can do the major breaking changes during the summer when most people are on holiday.

Thoughts, objections? @sebastianbaginski @thomasfanell @fredrikbryntesson @emilwestergren @davidpiuva ?

EDIT: It's decided. Here is what to do.

- [x] `source/uri`
- [x] `DateTime` and `TimeSpan`
- [x] `Cell` (and its extensions)
- [x] `source/unit`
- [x] `source/math`
- [x] `source/geometry` (breaks API)
- [x] `source/draw` (breaks API)
- [x] `CsvReader` and `CsvWriter` (breaks API)
- [x] `ArgumentParser` (breaks API)
- [x] `TextBuilder`
- [x] Any other minor uses
- [ ] Remove `Text`, `TextBuffer`

### PR DESCRIPTION
**Pull request by marcusnaslund**
Removes `Text`, `TextBuffer` and the support for text literals.

Will hold with this for a while.

Fixes #1724

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
Is `give() / take()` the next target ? ;)

**Comment by marcusnaslund** [comment]
Well.. :)

**Comment by emilwestergren** [comment]
So this entire project was just a huge waste of time?

**Comment by sebastianbaginski** [comment]
I think it gave birth to the `Owned Buffer` concept. Not really aware of any other benefits (and if we consider `owner` a benefit).

**Comment by marcusnaslund** [comment]
`Text` existed before I started, so I don't really know why it was created. I know Simon really pushed for its use and development, but noone who is here now seems to like it or really even understand its memory model very well. And with `String` working just great, it really brings nothing to the table.

**Comment by marcusnaslund** [comment]
Trying to write `text := t"i am a string literal"` in the code will not cause an insane segfault in rock, it will just say that the `Text` class is missing. Sometimes it seems perfectly sane.

**Comment by thomasfanell** [comment]
@marcusnaslund it was created because `String` used to leak memory, which is no longer the case (thank you, Sebastian)

**Comment by marcusnaslund** [comment]
Peer review and/or any last-minute objections @sebastianbaginski @fredrikbryntesson ?

**Comment by sebastianbaginski** [comment]
Nothing from me :+1:

**Comment by fredrikbryntesson** [comment]
Great :)

**Pull request merged**
