### PR TITLE
Removed GpuFence and OpenGLFence

### PR DESCRIPTION
**Pull request by emilwestergren**
Fixes https://github.com/magic-lang/ooc-kean/issues/1085
* Removed GpuFence
* Removed OpenGLFence
* Synchronizing is now done with `Promise/Future`

### CODE REVIEW

**Comment by emilwestergren** [comment]
@sebastianbaginski peer review

**Comment by emilwestergren** [comment]
@davidpiuva peer review

**Comment by davidpiuva** [comment]
I will be gone tomorrow but I can have a quick look before I go home.

**Comment by emilwestergren** [comment]
@davidpiuva peer reviewed it offline

**Comment by marcusnaslund** [comment]
Does not pass the API test.

**Comment by sebastianbaginski** [comment]
Failed with code 0 ...

**Comment by marcusnaslund** [comment]
> Failed with code 0 ...

Every failure seems to print that, but `PRInt` reports the exit code was 2.

**Comment by emilwestergren** [comment]
So what now?

**Comment by sebastianbaginski** [comment]
Try to build the library manually `./tools/build_library.sh`, if it does not work fix it or I can look into it if you don't have the time

**Comment by emilwestergren** [comment]
Strange, the error seems to be in `VidhanceContext` :
```
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc: In function ‘vidhance_sdk_VidhanceContext__VidhanceContextPC_init’:
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:116:5: error: unknown type name ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctx’
   this listen(func (frame: Frame) {
     ^
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:116:5: warning: implicit declaration of function ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctx_class’ [-Wimplicit-function-declaration]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:116:138: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   this listen(func (frame: Frame) {
                                                                                                                                          ^
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:116:50: error: ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctx’ undeclared (first use in this function)
   this listen(func (frame: Frame) {
                                                  ^
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:116:50: note: each undeclared identifier is reported only once for each function it appears in
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:116:125: error: expected ‘;’ before ‘{’ token
   this listen(func (frame: Frame) {
                                                                                                                             ^
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:117:9: error: ‘vidhance_sdk_VidhanceContext____vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_thunk’ undeclared (first use in this function)
    frame referenceCountIncrease()
         ^
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc: At top level:
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:264:99: error: unknown type name ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctx’
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:270:1: error: unknown type name ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctxClass’
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:270:81: error: conflicting types for ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctx_class’
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:116:153: note: previous implicit declaration of ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctx_class’ was here
   this listen(func (frame: Frame) {
                                                                                                                                                         ^
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc: In function ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctx_class’:
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:272:5: error: unknown type name ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctxClass’
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:274:9: warning: braces around scalar initializer [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:274:9: warning: (near initialization for ‘class’) [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:275:13: warning: braces around scalar initializer [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:275:13: warning: (near initialization for ‘class’) [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:276:17: warning: braces around scalar initializer [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:276:17: warning: (near initialization for ‘class’) [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:277:21: error: field name not in record or union initializer
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:277:21: error: (near initialization for ‘class’)
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:277:44: error: ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctx’ undeclared (first use in this function)
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:278:21: error: field name not in record or union initializer
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:278:21: error: (near initialization for ‘class’)
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:279:17: warning: excess elements in scalar initializer [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:279:17: warning: (near initialization for ‘class’) [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:280:17: error: field name not in record or union initializer
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:280:17: error: (near initialization for ‘class’)
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:280:17: warning: excess elements in scalar initializer [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:280:17: warning: (near initialization for ‘class’) [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:281:17: error: field name not in record or union initializer
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:281:17: error: (near initialization for ‘class’)
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:281:17: warning: excess elements in scalar initializer [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:281:17: warning: (near initialization for ‘class’) [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:282:17: error: field name not in record or union initializer
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:282:17: error: (near initialization for ‘class’)
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:282:17: warning: excess elements in scalar initializer [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:282:17: warning: (near initialization for ‘class’) [enabled by default]
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc: At top level:
/home/ewestergren/versioned/ooc/ooc-vidproc/source/vidhance/sdk/VidhanceContext.ooc:121:140: error: unknown type name ‘__vidhance_sdk_VidhanceContext_vidhance_sdk_VidhanceContext_closure22_ctx’
  free: override func {

```

**Comment by emilwestergren** [comment]
I get the same error with upstream

**Comment by emilwestergren** [comment]
Now it worked after `rock -x`

**Comment by marcusnaslund** [comment]
Yeah, I've noticed one always must `rock -x` before running the api test.

**Comment by marcusnaslund** [comment]
Just tested and upstream works for me too.

**Comment by emilwestergren** [comment]
Does the test script run `rock -x` before the API test?

**Comment by marcusnaslund** [comment]
Yes, that's how I discovered that. :)

**Comment by marcusnaslund** [comment]
The API test just passed in another PR, so something is wrong in this one.

**Comment by emilwestergren** [comment]
I don't get it, I passed the test locally with this branch.

**Comment by emilwestergren** [comment]
Just passed it again with `rock -x` before running the test...

**Comment by marcusnaslund** [comment]
Maybe PRInt has a bad day. I will restart when the network is stable.

**Comment by emilwestergren** [comment]
Seems unable to pass the API test. I don't know what to do here, it works fine locally.

**Comment by marcusnaslund** [comment]
I will wait and see if other kean PRs also fail the API test, then something's wrong in PRInt.

**Comment by marcusnaslund** [comment]
Well, you're off the hook, the API test fails for all kean PRs... for some reason.

**Comment by marcusnaslund** [comment]
I found the problem.

**Pull request merged**
