### PR TITLE
Fixed Windows incompability

### PR DESCRIPTION
**Pull request by davidpiuva**

### CODE REVIEW

**Comment by davidpiuva** [comment]
@sebastianbaginski Does this work better on Windows?

**Comment by sebastianbaginski** [comment]
Unfortunately no, still the same error
```
C:\msys32\home\user\ooc\ooc-kean\test\draw\DrawStateTest.ooc:31:30: error: two or more data types in declaration specifiers
    small := IntVector2D new(150, 100)
                              ^
C:\msys32\home\user\ooc\ooc-kean\test\draw\DrawStateTest.ooc:31:36: error: expected identifier or '(' before '=' token
    small := IntVector2D new(150, 100)

```

**Comment by davidpiuva** [comment]
Inlining the declarations to the calls worked on Sebastian's computer.

**Comment by davidpiuva** [comment]
Updated

**Comment by sebastianbaginski** [comment]
It works after @davidpiuva 's changes.

**Comment by marcusnaslund** [comment]
ping @thomasfanell

**Comment by marcusnaslund** [comment]
So this fixes #1464 ?

**Comment by davidpiuva** [comment]
Yes

**Pull request merged**
